#!/usr/bin/env bash
# Shared helpers for deploy/install.sh and deploy/rotate-basic-auth.sh.
set -euo pipefail

is_interactive_shell() {
  local tty_device=/dev/tty
  if [[ -e "${tty_device}" && -r "${tty_device}" ]]; then
    return 0
  fi
  if [[ -t 0 ]]; then
    return 0
  fi
  return 1
}

parse_env_value() {
  local value=$1
  if [[ "${value}" =~ ^\'(.*)\'$ ]]; then
    printf '%s' "${BASH_REMATCH[1]}"
  elif [[ "${value}" =~ ^\"(.*)\"$ ]]; then
    printf '%s' "${BASH_REMATCH[1]}"
  else
    printf '%s' "${value}"
  fi
}

load_environment_file() {
  local file=$1
  local line key raw_value value

  [[ -f "${file}" ]] || return 0

  while IFS= read -r line || [[ -n "${line}" ]]; do
    [[ "${line}" =~ ^[[:space:]]*# ]] && continue
    [[ "${line}" =~ ^[[:space:]]*$ ]] && continue
    [[ "${line}" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]] || continue
    key="${BASH_REMATCH[1]}"
    raw_value="${BASH_REMATCH[2]}"
    value="$(parse_env_value "${raw_value}")"
    printf -v "${key}" '%s' "${value}"
    export "${key?}"
  done <"${file}"
}

update_env_key() {
  local file=$1 key=$2 value=$3
  local tmp
  tmp="$(mktemp)"
  grep -v "^${key}=" "${file}" >"${tmp}" || true
  printf '%s=%s\n' "${key}" "${value}" >>"${tmp}"
  mv "${tmp}" "${file}"
}

hash_basic_auth_password() {
  local password=$1
  local runtime=${CLOUDVISION_MCP_RUNTIME:-podman}
  "${runtime}" run --rm docker.io/library/caddy:2-alpine \
    caddy hash-password --plaintext "${password}"
}

format_basic_auth_header() {
  local user=$1
  local password=$2
  local encoded
  encoded="$(printf '%s:%s' "${user}" "${password}" | base64 | tr -d '\n')"
  printf 'Basic %s' "${encoded}"
}

write_caddyfile() {
  local out=$1
  local host=$2
  local auth_mode=$3
  local basic_user=$4
  local basic_hash=$5
  local forward_url=$6
  {
    printf '%s\n' '# Generated by deploy scripts — use rotate-basic-auth.sh or install.sh to change auth.'
    printf '%s\n' '{'
    printf '\tadmin off\n'
    printf '%s\n' '}'
    printf '\n'
    printf '%s\n' "${host} {"
    printf '\ttls /opt/certs/wild/fullchain.pem /opt/certs/wild/privkey.pem\n'
    printf '\n'
    printf '\tencode zstd gzip\n'
    printf '\n'
    case "${auth_mode}" in
      basic)
        if [[ -z "${basic_hash}" ]]; then
          echo "basic auth selected but CLOUDVISION_MCP_BASIC_AUTH_HASH is empty" >&2
          exit 1
        fi
        printf '\tbasicauth {\n'
        printf '\t\t%s %s\n' "${basic_user}" "${basic_hash}"
        printf '\t}\n'
        printf '\n'
        ;;
      forward_auth)
        if [[ -z "${forward_url}" ]]; then
          echo "forward_auth selected but CLOUDVISION_MCP_FORWARD_AUTH_URL is empty" >&2
          exit 1
        fi
        printf '\tforward_auth %s {\n' "${forward_url}"
        printf '\t\turi /verify\n'
        printf '\t\tcopy_headers Remote-User Remote-Email X-Forwarded-User\n'
        printf '\t}\n'
        printf '\n'
        ;;
      none)
        echo "warning: CLOUDVISION_MCP_AUTH_MODE=none — MCP is TLS-only, no client auth." >&2
        ;;
      *)
        echo "Invalid CLOUDVISION_MCP_AUTH_MODE: ${auth_mode}" >&2
        exit 1
        ;;
    esac
    printf '\treverse_proxy http://127.0.0.1:8000 {\n'
    printf '\t\theader_up Host 127.0.0.1:8000\n'
    printf '\t\tflush_interval -1\n'
    printf '\t}\n'
    printf '%s\n' '}'
    printf '\n'
    printf '%s\n' ':80 {'
    printf '\tredir https://%s{uri} permanent\n' "${host}"
    printf '%s\n' '}'
  } >"${out}"
  chmod 644 "${out}"
}
